### ISSUE TITLE
No way to get videos

### ISSUE THREAD

**Issue by maxdmyers** [vfalies/tmdb#37]
I can add use the following code to get TMdb to return videos to me, but I have no way to access them using the Items\Movie class.

`$item->getMovie($movie['id'], ['append_to_response' => 'videos'])`

**Comment by vfalies** [comment]
It is a feature not yet implemented. I will develop it as soon as possible.

But, the implementation will not use your example. The second params 'option' of this call is to set option on response structure (as language of the response), not to add/search data.

I think that I will add some new methods to get this type of data.

**Comment by vfalies** [comment]
This feature is now available in release 1.7.

You can use it like this:
```php
$infos = $item->getMovie($movie['id']);
$responses = $infos->getVideos();

foreach ($responses as $response)
{
    echo $response->getName();
}
```

**Comment by maxdmyers** [comment]
Thank you! I've found your wrapper to be quite useful.

**Comment by maxdmyers** [comment]
Am I doing something incorrectly? I'm not getting any results back (I was with my implementation of getVideos - a lot rougher, but it worked).

`$item = new Item($this->tmdb);
$trailers = $item->getMovie(11)->getVideos();`
