### ISSUE TITLE
Contribution of Missing Endpoints & Daily File Exports

### ISSUE THREAD

**Issue by srichter** [vfalies/tmdb#40]
Great work on the foundations of this API wrapper. Would you accept pull requests to flush out the missing API endpoints?

Also, how would you like to see the [Daily File Exports](https://developers.themoviedb.org/3/getting-started/daily-file-exports) implemented? Since there's no authentication required for them and they're returned as gzipped non-standard json (json objects separated by newlines) they'd need their own parsing.

**Comment by vfalies** [comment]
Thank you ! Of course I accept pull requests to complete this API. If necessary I will comment them before merging.

Concerning the Daily File Exports, I don't had thinking about it. Therefore I'm open minded on the implementation. It must be generic to be use on the most simply and robust as possible.

**Comment by srichter** [comment]
Awesome, I will implement the missing endpoints as I need them in my project. I am working on the first one, TV Networks.

For the exports, I was thinking of adding a method in the Factory to get an "Export" object which will have its own implementation of the HTTPClient since we do not need the API key or other methods from the Tmdb class.

I also plan to implement:

- A way to choose between base_url and secure_base_url for a Media object
- Handling of svg Media paths (for TV Networks)
- A toString/toArray method on the Item Abstract. 

I'm also working on a Laravel package for this wrapper.

**Comment by vfalies** [comment]
TV Networks endpoint added in release 1.8
