### ISSUE TITLE
Adding getCast() for TV Shows?

### ISSUE THREAD

**Issue by mrrobotoz** [vfalies/tmdb#58]
Is there any way to get the cast of a tv show?

**Comment by vfalies** [comment]
Hi, not in the last release, I'm working on this feature for the next
release in a few days.

**Comment by mrrobotoz** [comment]
Ok, waiting to see!

**Comment by vfalies** [comment]
The release 1.12 allow to get cast and crew from TVShow / TVSeason and TVEpisode objects
