### ISSUE TITLE
Get poster/backdrop based on current movie

### ISSUE THREAD

**Issue by rollecode** [vfalies/tmdb#60]
It seems there's not enough documentation on how to fetch media? I see `poster_path` inside the array of `$movies->current()` and the example has media helper set like this:

```php
$media = new Media($tmdb);
$url = $media->getPosterUrl('/AbJBXaVPrdXROwb8KmgWUPU2XJX.jpg');
```

What is that jpg supposed to be in the documentation? How should I combine the find based on IMDb and this "media helper"? How to get poster or backdrop URL?

Sorry that I'm not familiar of this types of wrappers. `$movies->current()->getTitle()` and things like that are easy here but fetching media is a mystery here.

**Comment by vfalies** [comment]
If it's not clear I will enrich the documentation. 
For instance, if you will the poster and the backdrop of the movie "Star wars: Episode IV"

```php
$item  = new Item($tmdb);
$infos = $item->getMovie(11, array('language' => 'en-US'));

$backdrop_path = $infos->getBackdropPath();
$poster_path = $infos->getPosterPath();

$media = new Media($tmdb);
$poster_url = $media->getPosterUrl($posterpath);
$backdrop_url = $media->getBackdropUrl($backdroppath);
```

I hope that this example it's more clear
